#! /bin/zsh

export CLICOLOR=1

autoload -U is-at-least

setopt auto_cd              # do cd path if only 'path' is given as command
setopt correct              # try to correct command line
setopt correct_all       		# correct args
setopt complete_aliases			# dont replace alias before completion
setopt complete_in_word			# we want completion to be done from cursor in word
